"""create_episode_state_history_table

Revision ID: 6b158741b993
Revises: 14693b56ff22
Create Date: 2026-09-02 15:16:03.929351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b158741b993'
down_revision: Union[str, Sequence[str], None] = '14693b56ff22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode_state_history',
    sa.Column('history_id', sa.UUID(), nullable=False),
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('segment_dimension', sa.String(length=50), nullable=False),
    sa.Column('segment_value', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('effective_start_window', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index('ix_episode_state_history_as_of', 'episode_state_history', ['segment_dimension', 'segment_value', 'evaluation_timestamp'], unique=False)
    op.create_index('ix_episode_state_history_run', 'episode_state_history', ['reconciliation_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episode_state_history')
    # ### end Alembic commands ###
