"""Initial schema

Revision ID: ed7e2117b4b1
Revises: 
Create Date: 2026-09-01 18:30:56.963445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7e2117b4b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('source_event_id', sa.String(length=255), nullable=False),
    sa.Column('payment_id', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_minor_units', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('error_code', sa.String(length=255), nullable=True),
    sa.Column('error_description', sa.String(length=1024), nullable=True),
    sa.Column('error_source', sa.String(length=255), nullable=True),
    sa.Column('error_step', sa.String(length=255), nullable=True),
    sa.Column('error_reason', sa.String(length=255), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('source_system', 'source_event_id', name='uq_payment_event_source_identity')
    )
    op.create_table('raw_ingestion_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('source_event_id', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'source_event_id', name='uq_raw_ingestion_source_identity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_ingestion_records')
    op.drop_table('payment_events')
    # ### end Alembic commands ###
